version: '3.8'

services:
  # Serviço da API (Backend)
  backend:
    image: ${DOCKER_REGISTRY:-yourusername}/amazonia-experience:${TAG:-latest}
    # Para desenvolvimento, descomente estas linhas e comente a linha "image" acima
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    container_name: amazonia-experience-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      # Volumes para desenvolvimento (descomente para modo de desenvolvimento)
      # - ./src:/app/src
      # - ./tests:/app/tests
      - sqlite-data:/app/src/database
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-seu_jwt_secret_key_local}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-seu_refresh_token_secret_local}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-30d}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-15}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - CSP_DIRECTIVES=${CSP_DIRECTIVES:-default-src 'self'; script-src 'self'}
      - CACHE_VERSION=${CACHE_VERSION:-1.0.0}
      - OFFLINE_ANALYTICS_QUEUE_SIZE=${OFFLINE_ANALYTICS_QUEUE_SIZE:-20}
      - QUIZ_DEFAULT_TIMEOUT_MINUTES=${QUIZ_DEFAULT_TIMEOUT_MINUTES:-15}
      - QUIZ_MAX_ATTEMPTS_PER_DAY=${QUIZ_MAX_ATTEMPTS_PER_DAY:-5}
    # Para desenvolvimento, descomente esta linha
    # command: npm run dev
    networks:
      - amazonia-network

  # Frontend (adicione conforme necessário)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: amazonia-experience-client
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - amazonia-network

  # Ferramenta de administração para SQLite
  adminer:
    image: adminer
    container_name: amazonia-experience-adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    depends_on:
      - backend
    environment:
      - ADMINER_DEFAULT_SERVER=amazonia-experience-api
      - ADMINER_DESIGN=pepa-linha
    networks:
      - amazonia-network

networks:
  amazonia-network:
    driver: bridge

volumes:
  sqlite-data:
    driver: local