version: '3.8'

services:
  backend:
    build:
      context: .
      target: development
    container_name: amazonia-experience-backend
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}
      - JWT_SECRET=${JWT_SECRET:-desenvolvimento_jwt_secret}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-desenvolvimento_refresh_secret}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-30d}
      - DB_FILENAME=./src/database/dev.sqlite3
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - amazonia-network
    
  frontend:
    image: amazonia-experience-frontend:latest
    container_name: amazonia-experience-frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:3000
    networks:
      - amazonia-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  amazonia-network:
    driver: bridge

volumes:
  node_modules: